"""reach.tsv: which tool invokes which, one hop, and the generator that writes it (design §0 Selection, review S9g).

THE FILE. `<prefix>tests/reach.tsv`, one edge a line, `caller<TAB>callee`, both tool NAMES (a file's basename under
bin/, bin-private/ or core/bin/); `#` lines are comments. plan() runs a changed tool's own checks and the non-static
checks owning each of its direct callers. core/tests/reach.tsv holds core's edges only, so no overlay name enters
the published tree; the overlay's tests/reach.tsv holds bin-private's.

THE GENERATOR is the invocation grep tests/green.sh's land_scope uses: a caller names the callee as `${BIN}/t` or
`$BIN/t`, `$B/t`, `join(X, "t")` or `BIN / "t"`, the name ending at a character that cannot continue it. No self
edges; a tool named in `never` (core's `cc`, which names every tool) is never a caller. Output is sorted, so a
regenerated file diffs cleanly against the committed one:

    lander reach [--root DIR] [--callers DIR]… [--callees DIR]… [--never NAME]… [--check FILE]

prints the edges (default: callers and callees both bin/ under --root, never `cc`); --check FILE exits 1 and names
the difference when FILE's edges are not what the tree says.
"""
from __future__ import annotations

import os
import re
import sys

HEADER = "# reach.tsv: caller<TAB>callee, one hop, generated by `lander reach`; regenerate, do not edit by hand.\n"
_END = r"(?![A-Za-z0-9_-])"
USAGE = "usage: lander reach [--root DIR] [--callers DIR]… [--callees DIR]… [--never NAME]… [--check FILE]"


def parse(text: str) -> list:
    out = []
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) == 2 and parts[0] and parts[1]:
            out.append((parts[0].strip(), parts[1].strip()))
    return out


def callers(edges: list, name: str) -> list:
    return sorted({a for a, b in edges if b == name})


def pattern(t: str) -> re.Pattern:
    q = re.escape(t)
    return re.compile(rf"BIN\}}?/{q}{_END}|\$B/{q}{_END}|join\([A-Za-z_][A-Za-z0-9_]*, *[\"']{q}[\"']"
                      rf"|BIN */ *[\"']{q}[\"']")


def tools(root: str, dirs) -> dict:
    """name -> path of every regular file directly under each of dirs (relative to root)."""
    out = {}
    for d in dirs:
        full = os.path.join(root, d)
        for n in sorted(os.listdir(full)) if os.path.isdir(full) else []:
            if os.path.isfile(os.path.join(full, n)) and not n.startswith("."):
                out.setdefault(n, os.path.join(full, n))
    return out


def generate(root: str, caller_dirs=("bin",), callee_dirs=("bin",), never=("cc",)) -> list:
    callers_ = tools(root, caller_dirs)
    callees = tools(root, callee_dirs)
    texts = {}
    for n, p in callers_.items():
        try:
            with open(p, encoding="utf-8", errors="replace") as f:
                texts[n] = f.read()
        except OSError:
            texts[n] = ""
    edges = set()
    for t in callees:
        rx = pattern(t)
        for n, text in texts.items():
            if n != t and n not in never and rx.search(text):
                edges.add((n, t))
    return sorted(edges)


def render(edges: list) -> str:
    return HEADER + "".join(f"{a}\t{b}\n" for a, b in edges)


def cmd_reach(argv):
    root, cdirs, edirs, never, check = ".", [], [], [], ""
    it = iter(argv)
    for k in it:
        v = next(it, None)
        if v is None or k not in ("--root", "--callers", "--callees", "--never", "--check"):
            print(USAGE, file=sys.stderr)
            return 2
        if k == "--root":
            root = v
        elif k == "--callers":
            cdirs.append(v)
        elif k == "--callees":
            edirs.append(v)
        elif k == "--never":
            never.append(v)
        else:
            check = v
    edges = generate(root, cdirs or ["bin"], edirs or ["bin"], never or (["cc"] if not cdirs else []))
    if not check:
        sys.stdout.write(render(edges))
        return 0
    try:
        with open(check, encoding="utf-8") as f:
            have = set(parse(f.read()))
    except OSError as e:
        print(f"lander reach: {e}", file=sys.stderr)
        return 2
    want = set(edges)
    for a, b in sorted(want - have):
        print(f"lander reach: missing {a}\t{b}")
    for a, b in sorted(have - want):
        print(f"lander reach: stale   {a}\t{b}")
    print(f"lander reach: {check} {'matches the tree' if want == have else 'is out of date'}")
    return 0 if want == have else 1


COMMANDS = {"reach": (cmd_reach, "generate reach.tsv (who invokes whom, one hop), or --check a committed one")}
