"""reach.tsv: which tool invokes which, one hop, and the generator that writes it (design §0 Selection, review S9g).

THE FILE. `<prefix>tests/reach.tsv`, one edge a line, `caller<TAB>callee`, both tool NAMES (a file's basename under
bin/, bin-private/ or core/bin/); `#` lines are comments. plan() runs a changed tool's own checks and the non-static
checks owning each of its direct callers. core/tests/reach.tsv holds core's edges only, so no overlay name enters
the published tree; the overlay's tests/reach.tsv holds bin-private's.

THE GENERATOR is the invocation grep tests/green.sh's land_scope uses: a caller names the callee as `${BIN}/t` or
`$BIN/t`, `$B/t`, `join(X, "t")` or `BIN / "t"`, the name ending at a character that cannot continue it. No self
edges; a tool named in `never` (core's `cc`, which names every tool) is never a caller. Output is sorted, so a
regenerated file diffs cleanly against the committed one:

    lander reach [--root DIR] [--callers DIR]… [--callees DIR]… [--never NAME]… [--check FILE]

prints the edges (default: callers and callees both bin/ under --root, never `cc`); --check FILE exits 1 and names
the difference when FILE's edges are not what the tree says.

ON A GIT TREE. tree_edges(run, rev, prefix) is the same generator read out of a commit or tree, with the directories
each committed file's recipe names pinned per prefix (RECIPES; a tree laid out otherwise proves nothing), and generated_change says whether the edges a change adds to the reach file
are all ones the generator writes there and the edges it drops all ones it does not. Both read only through `run`, a
git.sealed() runner, so no replace ref, graft, config or merge driver of the checkout's can shape what they see; a
blob is asked for by its id, never through line-based batch input; and a tool name holding a control character,
or a symlinked tool whose target is not a regular file in the tree, proves nothing. plan() asks it of a PR's merge tree against the base: a change that agrees follows from the code and
does not make the PR lander-class; one that does not, or that git cannot prove, still does. generate_at(repo, rev,
prefix) is tree_edges on a commit of a checkout, sealed.
"""
from __future__ import annotations

import os
import posixpath
import re
import sys
import unicodedata

HEADER = "# reach.tsv: caller<TAB>callee, one hop, generated by `lander reach`; regenerate, do not edit by hand.\n"
_END = r"(?![A-Za-z0-9_-])"
USAGE = "usage: lander reach [--root DIR] [--callers DIR]… [--callees DIR]… [--never NAME]… [--check FILE]"


def parse(text: str) -> list:
    out = []
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) == 2 and parts[0] and parts[1]:
            out.append((parts[0].strip(), parts[1].strip()))
    return out


def callers(edges: list, name: str) -> list:
    return sorted({a for a, b in edges if b == name})


def pattern(t: str) -> re.Pattern:
    q = re.escape(t)
    return re.compile(rf"BIN\}}?/{q}{_END}|\$B/{q}{_END}|join\([A-Za-z_][A-Za-z0-9_]*, *[\"']{q}[\"']"
                      rf"|BIN */ *[\"']{q}[\"']")


def tools(root: str, dirs) -> dict:
    """name -> path of every regular file directly under each of dirs (relative to root)."""
    out = {}
    for d in dirs:
        full = os.path.join(root, d)
        for n in sorted(os.listdir(full)) if os.path.isdir(full) else []:
            if os.path.isfile(os.path.join(full, n)) and not n.startswith("."):
                out.setdefault(n, os.path.join(full, n))
    return out


def edges_of(texts: dict, callees, never=("cc",)) -> list:
    """The edges from each caller (name -> its text) to each callee name."""
    edges = set()
    for t in callees:
        rx = pattern(t)
        for n, text in texts.items():
            if n != t and n not in never and rx.search(text):
                edges.add((n, t))
    return sorted(edges)


def generate(root: str, caller_dirs=("bin",), callee_dirs=("bin",), never=("cc",)) -> list:
    callers_ = tools(root, caller_dirs)
    texts = {}
    for n, p in callers_.items():
        try:
            with open(p, encoding="utf-8", errors="replace") as f:
                texts[n] = f.read()
        except OSError:
            texts[n] = ""
    return edges_of(texts, tools(root, callee_dirs), never)


def _bad_name(name: str) -> bool:
    """A name git could not hand over as it is: one with a control character (a newline, a tab, DEL, a C1 code) or
    bytes that are not UTF-8 (read back as U+FFFD)."""
    return "�" in name or any(unicodedata.category(c) == "Cc" for c in name)


def _ls(run, rev: str, path: str) -> list:
    """[(mode, type, oid, path)] of `ls-tree -z <rev> -- <path>`, read through `run` (a git.sealed() runner, whose
    env makes every pathspec literal). Raises OSError when git fails or a row is not one ls-tree writes."""
    rc, out = run("ls-tree", "-z", rev, "--", path)
    if rc:
        raise OSError(f"git ls-tree {rev[:12]} {path}: {str(out).strip()[-300:]}")
    rows = []
    for row in out.split("\0"):
        if not row:
            continue
        meta, tab, p = row.partition("\t")
        f = meta.split(" ")
        if not tab or len(f) != 3:
            raise OSError(f"git ls-tree {rev[:12]}: not a row: {row[:80]!r}")
        rows.append((f[0], f[1], f[2], p))
    return rows


def _blob(run, oid: str) -> str:
    """The text of one blob, asked for by its id alone: no path goes through git's line-based batch input, so a name
    holding a newline cannot shift one file's text onto another. Raises OSError when git fails."""
    rc, out = run("cat-file", "blob", oid)
    if rc:
        raise OSError(f"git cat-file blob {oid[:12]}: {str(out).strip()[-300:]}")
    return out


def _text_at(run, rev: str, path: str):
    """The text of the regular file at <rev>:<path>, or None when the path is missing there. Raises OSError when it
    is there but something else (a symlink, a directory, a submodule)."""
    rows = [r for r in _ls(run, rev, path) if r[3] == path]
    if not rows:
        return None
    if len(rows) != 1 or rows[0][0] not in REGULAR or rows[0][1] != "blob":
        raise OSError(f"{path!r} at {rev[:12]} is not a regular file")
    return _blob(run, rows[0][2])


# prefix -> (caller dirs, callee dirs, never), each dir under the prefix: the recipe each committed reach file names
# (core/tests/reach.tsv: `lander reach` from core/, bin/ to bin/, never cc; tests/reach.tsv: bin-private/ to
# bin-private/ or core/bin/). Pinned, so a PR cannot pick the recipe by adding or emptying a directory.
RECIPES = {"core/": (("bin",), ("bin",), ("cc",)),
           "": (("bin-private",), ("bin-private", "core/bin"), ())}
# directories whose presence means the tree is not laid out as the recipe expects
FOREIGN = {"": ("bin",), "core/": ()}
REGULAR = ("100644", "100755")


def _regular(run, rev: str, path: str, mode: str, oid: str) -> str:
    """The blob id a tool at <path> reads as: its own for a regular file, its target's for a symlink to a regular
    file inside the tree. A link to a link, to a directory, out of the tree or to nothing raises OSError: a checkout
    resolves those differently (open() follows every hop, isfile() drops a dangling one), so they prove nothing."""
    if mode in REGULAR:
        return oid
    text = _blob(run, oid)
    target = posixpath.normpath(posixpath.join(posixpath.dirname(path), text))
    if not text or _bad_name(text) or target.startswith(("/", "../")) or target in ("..", "."):
        raise OSError(f"{path!r} links out of the tree ({text!r}), which proves nothing")
    rows = [r for r in _ls(run, rev, target) if r[3] == target]
    if len(rows) != 1 or rows[0][0] not in REGULAR or rows[0][1] != "blob":
        raise OSError(f"{path!r} links to {target!r}, which is not a regular file, so it proves nothing")
    return rows[0][2]


def tree_edges(run, rev: str, prefix: str) -> list:
    """What the generator writes for <prefix>tests/reach.tsv, read out of a git tree (a commit or tree id) through
    `run`, a git.sealed() runner, rather than a checkout, with the prefix's pinned recipe (RECIPES). A symlinked tool
    is read at its target when that is a regular file inside the tree. Raises OSError, so a caller never takes it for
    a match, when git cannot list or read the tree, the prefix has no recipe, a recipe directory holds no tool or a
    FOREIGN one exists, a name there holds a control character, or a tool is any other symlink."""
    if prefix not in RECIPES:
        raise OSError(f"no reach recipe for {prefix!r}")
    caller_dirs, callee_dirs, never = RECIPES[prefix]
    for d in FOREIGN[prefix]:
        if _ls(run, rev, f"{prefix}{d}"):
            raise OSError(f"{prefix}{d} exists, which the {prefix or 'overlay'} reach recipe does not read")
    entries = {}   # dir -> [(name, path, mode, oid)] of the non-dot files and symlinks directly under it
    for d in dict.fromkeys(caller_dirs + callee_dirs):
        rows = []
        for mode, _, oid, path in _ls(run, rev, f"{prefix}{d}/"):
            name = path[len(prefix) + len(d) + 1:]
            if _bad_name(path):
                raise OSError(f"{path!r}: a control character in a tool's name proves nothing")
            if mode in REGULAR + ("120000",) and name and "/" not in name and not name.startswith("."):
                rows.append((name, path, _regular(run, rev, path, mode, oid)))
        if not rows:
            raise OSError(f"{prefix}{d}/ holds no tool, which the reach recipe does not expect")
        entries[d] = sorted(rows)
    blobs = {}   # name -> blob id, the first directory's file winning as tools() has it
    for d in caller_dirs:
        for name, _, oid in entries[d]:
            blobs.setdefault(name, oid)
    texts = {name: _blob(run, oid) for name, oid in blobs.items()}
    callees = sorted({name for d in callee_dirs for name, _, _ in entries[d]})
    return edges_of(texts, callees, never)


def generate_at(repo_root: str, rev: str, prefix: str) -> list:
    """tree_edges() of commit <rev> of the repo at repo_root, read sealed (git.sealed: no replace ref, graft, config
    or attribute of the checkout's reaches it). Raises OSError when git cannot read it."""
    from lander import git as G
    with G.sealed(repo_root, rev) as ((rc, out), run):
        if run is None:
            raise OSError(f"git could not read {rev[:12]} sealed: {str(out).strip()[-300:]}")
        return tree_edges(run, out[0], prefix)


def generated_change(run, base: str, rev: str, prefix: str) -> bool:
    """True when every edge <prefix>tests/reach.tsv gains from base to rev is one tree_edges writes at rev, and
    every edge it loses is one tree_edges does not write there, both read through `run`, a git.sealed() runner.
    Edges the change leaves alone are not judged, so drift already on the base (an edge an earlier change never
    added) does not stop it. Comments and lines that are not edges are read by nothing (parse skips them), so they are
    not compared. A file rev lacks, or anything git cannot answer, is False: only a proven match counts."""
    path = f"{prefix}tests/reach.tsv"
    try:
        was, now = _text_at(run, base, path), _text_at(run, rev, path)
        if now is None:
            return False
        was, now = set(parse(was or "")), set(parse(now))
        want = set(tree_edges(run, rev, prefix))
        return now - was <= want and not (was - now) & want
    except (OSError, ValueError):
        return False


def render(edges: list) -> str:
    return HEADER + "".join(f"{a}\t{b}\n" for a, b in edges)


def cmd_reach(argv):
    root, cdirs, edirs, never, check = ".", [], [], [], ""
    it = iter(argv)
    for k in it:
        v = next(it, None)
        if v is None or k not in ("--root", "--callers", "--callees", "--never", "--check"):
            print(USAGE, file=sys.stderr)
            return 2
        if k == "--root":
            root = v
        elif k == "--callers":
            cdirs.append(v)
        elif k == "--callees":
            edirs.append(v)
        elif k == "--never":
            never.append(v)
        else:
            check = v
    edges = generate(root, cdirs or ["bin"], edirs or ["bin"], never or (["cc"] if not cdirs else []))
    if not check:
        sys.stdout.write(render(edges))
        return 0
    try:
        with open(check, encoding="utf-8") as f:
            have = set(parse(f.read()))
    except OSError as e:
        print(f"lander reach: {e}", file=sys.stderr)
        return 2
    want = set(edges)
    for a, b in sorted(want - have):
        print(f"lander reach: missing {a}\t{b}")
    for a, b in sorted(have - want):
        print(f"lander reach: stale   {a}\t{b}")
    print(f"lander reach: {check} {'matches the tree' if want == have else 'is out of date'}")
    return 0 if want == have else 1


COMMANDS = {"reach": (cmd_reach, "generate reach.tsv (who invokes whom, one hop), or --check a committed one")}
